# Generated by Django 5.0.6 on 2024-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
    ]
