# Generated by Django 5.0.6 on 2024-08-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_webpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
