# Generated by Django 5.0.6 on 2024-08-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_webpage_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='report',
            field=models.JSONField(default=dict),
        ),
    ]
