# Generated by Django 5.0.6 on 2024-08-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_webpage_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='report',
        ),
        migrations.AddField(
            model_name='webpage',
            name='report_html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
