# Generated by Django 5.0.6 on 2024-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_remove_webpage_report_webpage_report_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='report_html',
        ),
        migrations.AddField(
            model_name='webpage',
            name='report',
            field=models.JSONField(default=dict),
        ),
    ]
